# -*- coding: utf-8 -*-
"""mecanica_problema_dois_corpos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLsoM15IVsqTZmQXcipnEkrTzaXk3W4y
"""

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
from matplotlib import animation


# ============================================================
# Funções auxiliares gerais
# ============================================================

def com_pos(m1, r1, m2, r2):
    return (m1 * r1 + m2 * r2) / (m1 + m2)


def com_vel(m1, v1, m2, v2):
    return (m1 * v1 + m2 * v2) / (m1 + m2)


def massa_no_tempo(t, m0, tau, massa_variavel):
    """
    Massa constante:
        m(t) = m0

    Massa variável:
        m(t) = m0 * exp(-t/tau)

    A função funciona tanto para t escalar quanto para t vetor.
    """

    t_array = np.asarray(t, dtype=float)

    if massa_variavel:
        massa = m0 * np.exp(-t_array / tau)
    else:
        massa = np.full_like(t_array, m0, dtype=float)

    if massa.ndim == 0:
        return float(massa)

    return massa


def nome_arquivo_seguro(nome):
    nome = nome.lower()
    nome = nome.replace(" ", "_")
    nome = nome.replace(":", "")
    nome = nome.replace(",", "")
    nome = nome.replace("-", "_")
    nome = nome.replace("ç", "c")
    nome = nome.replace("ã", "a")
    nome = nome.replace("á", "a")
    nome = nome.replace("à", "a")
    nome = nome.replace("â", "a")
    nome = nome.replace("é", "e")
    nome = nome.replace("ê", "e")
    nome = nome.replace("í", "i")
    nome = nome.replace("ó", "o")
    nome = nome.replace("ô", "o")
    nome = nome.replace("ú", "u")
    nome = nome.replace("__", "_")

    return nome + ".mp4"


def set_axes_equal_3d(ax, r1_sol, r2_sol, r_com_sol=None, fator_visual_z=0.75):
    """
    Ajusta os limites dos eixos 3D.

    fator_visual_z:
        - 1.00 mantém escala completamente igual.
        - menor que 1.00 deixa o eixo z visualmente mais destacado.
        - isso não altera a física, só o enquadramento visual.
    """

    arrays_x = [r1_sol[:, 0], r2_sol[:, 0]]
    arrays_y = [r1_sol[:, 1], r2_sol[:, 1]]
    arrays_z = [r1_sol[:, 2], r2_sol[:, 2]]

    if r_com_sol is not None:
        arrays_x.append(r_com_sol[:, 0])
        arrays_y.append(r_com_sol[:, 1])
        arrays_z.append(r_com_sol[:, 2])

    all_x = np.concatenate(arrays_x)
    all_y = np.concatenate(arrays_y)
    all_z = np.concatenate(arrays_z)

    x_min, x_max = all_x.min(), all_x.max()
    y_min, y_max = all_y.min(), all_y.max()
    z_min, z_max = all_z.min(), all_z.max()

    x_range = x_max - x_min
    y_range = y_max - y_min
    z_range = z_max - z_min

    max_range = max(x_range, y_range, z_range, 1.0)

    x_mid = 0.5 * (x_max + x_min)
    y_mid = 0.5 * (y_max + y_min)
    z_mid = 0.5 * (z_max + z_min)

    margin = 0.15
    lim = 0.5 * max_range * (1.0 + margin)

    ax.set_xlim(x_mid - lim, x_mid + lim)
    ax.set_ylim(y_mid - lim, y_mid + lim)
    ax.set_zlim(z_mid - lim * fator_visual_z, z_mid + lim * fator_visual_z)


# ============================================================
# Equações diferenciais do problema de dois corpos
# ============================================================

def two_body_eqn(t, w, G, m10, m20, eps, massa_variavel, tau1, tau2):
    r1 = w[0:3]
    r2 = w[3:6]
    v1 = w[6:9]
    v2 = w[9:12]

    m1_t = massa_no_tempo(t, m10, tau1, massa_variavel)
    m2_t = massa_no_tempo(t, m20, tau2, massa_variavel)

    r12 = r2 - r1

    dist2 = np.dot(r12, r12) + eps**2
    dist = np.sqrt(dist2)

    a1 = G * m2_t * r12 / dist**3
    a2 = -G * m1_t * r12 / dist**3

    derivs = np.concatenate((v1, v2, a1, a2))

    return derivs


# ============================================================
# Grandezas físicas
# ============================================================

def energia_total(r1, r2, v1, v2, G, m1_series, m2_series, eps):
    r12 = r2 - r1
    dist = np.sqrt(np.sum(r12**2, axis=1) + eps**2)

    T = (
        0.5 * m1_series * np.sum(v1**2, axis=1)
        + 0.5 * m2_series * np.sum(v2**2, axis=1)
    )

    U = -G * m1_series * m2_series / dist

    return T + U


def momento_linear_total(v1, v2, m1_series, m2_series):
    return m1_series[:, None] * v1 + m2_series[:, None] * v2


def momento_angular_total(r1, r2, v1, v2, m1_series, m2_series):
    L1 = np.cross(r1, m1_series[:, None] * v1)
    L2 = np.cross(r2, m2_series[:, None] * v2)

    return L1 + L2


# ============================================================
# Função principal de simulação 3D
# ============================================================

def simular_dois_corpos_3d(
    nome_caso,
    G,
    m1,
    m2,
    eps,
    r1_0,
    r2_0,
    v1_0,
    v2_0,
    V_CM=None,
    massa_variavel=False,
    tau1=None,
    tau2=None,
    t_final=20.0,
    n_points=4000,
    skip=4,
    fps=30,
    dpi=200,
    salvar_video=True,
    mostrar_grafico_estatico=True
):
    print("\n======================================================")
    print(f"Rodando simulação: {nome_caso}")
    print("======================================================")

    if massa_variavel:
        if tau1 is None or tau2 is None:
            raise ValueError("Para massa variável, tau1 e tau2 precisam ser definidos.")

    r1_0 = np.array(r1_0, dtype=float)
    r2_0 = np.array(r2_0, dtype=float)
    v1_0 = np.array(v1_0, dtype=float)
    v2_0 = np.array(v2_0, dtype=float)

    if V_CM is None:
        V_CM = np.array([0.0, 0.0, 0.0], dtype=float)
    else:
        V_CM = np.array(V_CM, dtype=float)

    v1_0 = v1_0 + V_CM
    v2_0 = v2_0 + V_CM

    r_com_0 = com_pos(m1, r1_0, m2, r2_0)
    v_com_0 = com_vel(m1, v1_0, m2, v2_0)

    print("G  =", G)
    print("m1 inicial =", m1)
    print("m2 inicial =", m2)
    print("m1/m2 inicial =", m1 / m2)
    print("eps =", eps)
    print("massa_variavel =", massa_variavel)

    if massa_variavel:
        print("tau1 =", tau1)
        print("tau2 =", tau2)
        print("m1(t_final)/m1(0) =", np.exp(-t_final / tau1))
        print("m2(t_final)/m2(0) =", np.exp(-t_final / tau2))

    print("V_CM =", V_CM)
    print("r1(0) =", r1_0)
    print("r2(0) =", r2_0)
    print("v1(0) após V_CM =", v1_0)
    print("v2(0) após V_CM =", v2_0)
    print("Centro de massa inicial:", r_com_0)
    print("Velocidade inicial do centro de massa:", v_com_0)

    init_params = np.concatenate((r1_0, r2_0, v1_0, v2_0))

    time_span = np.linspace(0.0, t_final, n_points)

    sol_object = solve_ivp(
        two_body_eqn,
        [0.0, t_final],
        init_params,
        t_eval=time_span,
        args=(G, m1, m2, eps, massa_variavel, tau1, tau2),
        method="DOP853",
        rtol=1e-10,
        atol=1e-10
    )

    if not sol_object.success:
        print("A integração falhou:")
        print(sol_object.message)
        return None

    solution = sol_object.y.T

    r1_sol = solution[:, 0:3]
    r2_sol = solution[:, 3:6]
    v1_sol = solution[:, 6:9]
    v2_sol = solution[:, 9:12]

    m1_series = massa_no_tempo(time_span, m1, tau1, massa_variavel)
    m2_series = massa_no_tempo(time_span, m2, tau2, massa_variavel)

    r_com_sol = (
        m1_series[:, None] * r1_sol
        + m2_series[:, None] * r2_sol
    ) / (m1_series[:, None] + m2_series[:, None])

    E = energia_total(r1_sol, r2_sol, v1_sol, v2_sol, G, m1_series, m2_series, eps)
    P = momento_linear_total(v1_sol, v2_sol, m1_series, m2_series)
    L = momento_angular_total(r1_sol, r2_sol, v1_sol, v2_sol, m1_series, m2_series)

    E0 = E[0]
    Ef = E[-1]

    if abs(E0) > 1e-14:
        variacao_relativa_E = abs((Ef - E0) / E0)
    else:
        variacao_relativa_E = abs(Ef - E0)

    print("\n--- Grandezas físicas ---")
    print("Energia inicial:", E0)
    print("Energia final:  ", Ef)
    print("Variação relativa da energia:", variacao_relativa_E)
    print("Momento linear inicial:", P[0])
    print("Momento linear final:  ", P[-1])
    print("Variação do momento linear:", P[-1] - P[0])
    print("Momento angular inicial:", L[0])
    print("Momento angular final:  ", L[-1])
    print("Variação do momento angular:", L[-1] - L[0])

    if massa_variavel:
        print("\nObservação:")
        print("Como as massas variam com o tempo, energia, momento linear e momento angular")
        print("dos dois corpos restantes não precisam ser conservados.")

    # ========================================================
    # Gráfico estático 3D
    # ========================================================

    if mostrar_grafico_estatico:
        fig_static = plt.figure(figsize=(9, 8))
        ax_static = fig_static.add_subplot(111, projection="3d")

        ax_static.plot(r1_sol[:, 0], r1_sol[:, 1], r1_sol[:, 2], color="darkblue", label="Corpo 1")
        ax_static.plot(r2_sol[:, 0], r2_sol[:, 1], r2_sol[:, 2], color="red", label="Corpo 2")
        ax_static.plot(r_com_sol[:, 0], r_com_sol[:, 1], r_com_sol[:, 2], color="black", linestyle="--", label="Centro de massa")

        ax_static.scatter(r1_sol[0, 0], r1_sol[0, 1], r1_sol[0, 2], color="darkblue", s=80)
        ax_static.scatter(r2_sol[0, 0], r2_sol[0, 1], r2_sol[0, 2], color="red", s=80)
        ax_static.scatter(r_com_sol[0, 0], r_com_sol[0, 1], r_com_sol[0, 2], color="black", s=40)

        ax_static.set_xlabel("x")
        ax_static.set_ylabel("y")
        ax_static.set_zlabel("z")
        ax_static.set_title(nome_caso, pad=20)

        ax_static.view_init(elev=25, azim=35)
        ax_static.legend(loc="lower left")

        set_axes_equal_3d(ax_static, r1_sol, r2_sol, r_com_sol, fator_visual_z=0.75)

        plt.show()

    # ========================================================
    # Animação 3D
    # ========================================================

    r1_anim = r1_sol[::skip]
    r2_anim = r2_sol[::skip]
    r_com_anim = r_com_sol[::skip]
    time_anim = time_span[::skip]

    m1_anim = m1_series[::skip]

    m2_anim = m2_series[::skip]

    frames = len(r1_anim)

    fig = plt.figure(figsize=(9, 8))
    ax = fig.add_subplot(111, projection="3d")

    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_zlabel("z")
    ax.set_title(nome_caso, pad=20)

    ax.view_init(elev=25, azim=35)

    set_axes_equal_3d(ax, r1_sol, r2_sol, r_com_sol, fator_visual_z=0.75)

    line1, = ax.plot([], [], [], color="darkblue", label="Corpo 1")
    line2, = ax.plot([], [], [], color="red", label="Corpo 2")
    line_com, = ax.plot([], [], [], color="black", linestyle="--", label="Centro de massa")

    point1, = ax.plot([], [], [], "o", color="darkblue", markersize=8)
    point2, = ax.plot([], [], [], "o", color="red", markersize=8)
    point_com, = ax.plot([], [], [], "o", color="black", markersize=5)

    ax.legend(loc="lower left")

    info_text = ax.text2D(
        0.98,
        0.95,
        "",
        transform=ax.transAxes,
        fontsize=10,
        ha="right",
        va="top",
        bbox=dict(facecolor='white', alpha=0.7, edgecolor='none', pad=5)
    )

    def init_animation():
        line1.set_data([], [])
        line1.set_3d_properties([])

        line2.set_data([], [])
        line2.set_3d_properties([])

        line_com.set_data([], [])
        line_com.set_3d_properties([])

        point1.set_data([], [])
        point1.set_3d_properties([])

        point2.set_data([], [])
        point2.set_3d_properties([])

        point_com.set_data([], [])
        point_com.set_3d_properties([])

        info_text.set_text("")

        return line1, line2, line_com, point1, point2, point_com, info_text

    def animate(i):
        line1.set_data(r1_anim[:i + 1, 0], r1_anim[:i + 1, 1])
        line1.set_3d_properties(r1_anim[:i + 1, 2])

        line2.set_data(r2_anim[:i + 1, 0], r2_anim[:i + 1, 1])
        line2.set_3d_properties(r2_anim[:i + 1, 2])

        line_com.set_data(r_com_anim[:i + 1, 0], r_com_anim[:i + 1, 1])
        line_com.set_3d_properties(r_com_anim[:i + 1, 2])

        point1.set_data([r1_anim[i, 0]], [r1_anim[i, 1]])
        point1.set_3d_properties([r1_anim[i, 2]])

        point2.set_data([r2_anim[i, 0]], [r2_anim[i, 1]])
        point2.set_3d_properties([r2_anim[i, 2]])

        point_com.set_data([r_com_anim[i, 0]], [r_com_anim[i, 1]])
        point_com.set_3d_properties([r_com_anim[i, 2]])

        if massa_variavel:
            info_text.set_text(
                f"t = {time_anim[i]:.2f}\n"
                f"Massa 1 restante (t/0) = {m1_anim[i] / m1:.3f}\n"
                f"Massa 2 restante (t/0) = {m2_anim[i] / m2:.3f}"
            )
        else:
            info_text.set_text(f"t = {time_anim[i]:.2f}")

        ax.view_init(elev=25, azim=35)

        return line1, line2, line_com, point1, point2, point_com, info_text

    anim = animation.FuncAnimation(
        fig,
        animate,
        init_func=init_animation,
        frames=frames,
        interval=20,
        blit=False
    )

    nome_video = nome_arquivo_seguro(nome_caso)

    if salvar_video:
        Writer = animation.writers["ffmpeg"]
        writer = Writer(fps=fps, metadata=dict(artist="MCQ"), bitrate=4000)

        anim.save(nome_video, writer=writer, dpi=dpi)

        print("\nVídeo salvo como:", nome_video)

    plt.close(fig)

    return {
        "time": time_span,
        "r1": r1_sol,
        "r2": r2_sol,
        "v1": v1_sol,
        "v2": v2_sol,
        "r_com": r_com_sol,
        "m1_t": m1_series,
        "m2_t": m2_series,
        "E": E,
        "P": P,
        "L": L,
        "video": nome_video
    }


# ============================================================
# Definição dos cenários
# ============================================================

G = 1.0
eps = 0.03

casos = []


# ============================================================
# CENÁRIO 1 - MASSAS IGUAIS
# ============================================================

casos.append({
    "nome": "Cenario 1 - Massas iguais - Proximas em repouso",
    "G": G, "m1": 1.0, "m2": 1.0, "eps": eps,
    "r1": [-0.5, 0.0, 0.0],
    "r2": [0.5, 0.0, 0.0],
    "v1": [0.0, 0.0, 0.0],
    "v2": [0.0, 0.0, 0.0],
    "V_CM": [0.0, 0.0, 0.10],
    "massa_variavel": False, "tau1": None, "tau2": None,
    "t_final": 8.0
})

casos.append({
    "nome": "Cenario 1 - Massas iguais - Proximas com velocidade",
    "G": G, "m1": 1.0, "m2": 1.0, "eps": eps,
    "r1": [-0.5, 0.0, 0.0],
    "r2": [0.5, 0.0, 0.0],
    "v1": [0.0, -0.5, 0.0],
    "v2": [0.0, 0.5, 0.0],
    "V_CM": [0.0, 0.0, 0.10],
    "massa_variavel": False, "tau1": None, "tau2": None,
    "t_final": 25.0
})

casos.append({
    "nome": "Cenario 1 - Massas iguais - Distantes em repouso",
    "G": G, "m1": 1.0, "m2": 1.0, "eps": eps,
    "r1": [-2.0, 0.0, 0.0],
    "r2": [2.0, 0.0, 0.0],
    "v1": [0.0, 0.0, 0.0],
    "v2": [0.0, 0.0, 0.0],
    "V_CM": [0.0, 0.0, 0.08],
    "massa_variavel": False, "tau1": None, "tau2": None,
    "t_final": 20.0
})

casos.append({
    "nome": "Cenario 1 - Massas iguais - Distantes com velocidade",
    "G": G, "m1": 1.0, "m2": 1.0, "eps": eps,
    "r1": [-2.0, 0.0, 0.0],
    "r2": [2.0, 0.0, 0.0],
    "v1": [0.0, -0.35, 0.0],
    "v2": [0.0, 0.35, 0.0],
    "V_CM": [0.0, 0.0, 0.08],
    "massa_variavel": False, "tau1": None, "tau2": None,
    "t_final": 35.0
})


# ============================================================
# CENÁRIO 2 - MASSAS DIFERENTES
# ============================================================

casos.append({
    "nome": "Cenario 2 - Massas diferentes - Proximas em repouso",
    "G": G, "m1": 1.0, "m2": 1.0 / 333000.0, "eps": eps,
    "r1": [0.0, 0.0, 0.0],
    "r2": [0.8, 0.0, 0.0],
    "v1": [0.0, 0.0, 0.0],
    "v2": [0.0, 0.0, 0.0],
    "V_CM": [0.0, 0.0, 0.08],
    "massa_variavel": False, "tau1": None, "tau2": None,
    "t_final": 8.0
})

casos.append({
    "nome": "Cenario 2 - Massas diferentes - Proximas com velocidade",
    "G": G, "m1": 1.0, "m2": 1.0 / 333000.0, "eps": eps,
    "r1": [0.0, 0.0, 0.0],
    "r2": [0.8, 0.0, 0.0],
    "v1": [0.0, 0.0, 0.0],
    "v2": [0.0, 1.10, 0.0],
    "V_CM": [0.0, 0.0, 0.08],
    "massa_variavel": False, "tau1": None, "tau2": None,
    "t_final": 20.0
})

casos.append({
    "nome": "Cenario 2 - Massas diferentes - Distantes em repouso",
    "G": G, "m1": 1.0, "m2": 1.0 / 333000.0, "eps": eps,
    "r1": [0.0, 0.0, 0.0],
    "r2": [3.0, 0.0, 0.0],
    "v1": [0.0, 0.0, 0.0],
    "v2": [0.0, 0.0, 0.0],
    "V_CM": [0.0, 0.0, 0.06],
    "massa_variavel": False, "tau1": None, "tau2": None,
    "t_final": 30.0
})

casos.append({
    "nome": "Cenario 2 - Massas diferentes - Distantes com velocidade",
    "G": G, "m1": 1.0, "m2": 1.0 / 333000.0, "eps": eps,
    "r1": [0.0, 0.0, 0.0],
    "r2": [3.0, 0.0, 0.0],
    "v1": [0.0, 0.0, 0.0],
    "v2": [0.0, 0.577, 0.0],
    "V_CM": [0.0, 0.0, 0.06],
    "massa_variavel": False, "tau1": None, "tau2": None,
    "t_final": 40.0
})


# ============================================================
# ITEM 7 - MASSAS VARIÁVEIS
# ============================================================

casos.append({
    "nome": "Item 7 - Cenario 1 - Massas iguais - Perda Assimétrica",
    "G": G, "m1": 1.0, "m2": 1.0, "eps": eps,
    "r1": [-0.5, 0.0, 0.0],
    "r2": [0.5, 0.0, 0.0],
    "v1": [0.0, -0.5, 0.0],
    "v2": [0.0, 0.5, 0.0],
    "V_CM": [0.0, 0.0, 0.10],
    "massa_variavel": True, "tau1": 15.0, "tau2": 150.0,
    "t_final": 25.0
})

casos.append({
    "nome": "Item 7 - Cenario 2 - Massas diferentes - Estrela com perda moderada",
    "G": G, "m1": 1.0, "m2": 1.0 / 333000.0, "eps": eps,
    "r1": [0.0, 0.0, 0.0],
    "r2": [3.0, 0.0, 0.0],
    "v1": [0.0, 0.0, 0.0],
    "v2": [0.0, 0.577, 0.0],
    "V_CM": [0.0, 0.0, 0.06],
    "massa_variavel": True, "tau1": 60.0, "tau2": 1000.0,
    "t_final": 70.0
})


# ============================================================
# Rodar as simulações
# ============================================================
#
# Para um vídeo específico:
#   casos_para_rodar = [casos[indice]]
#
# Para todos os 10 vídeos:
#   casos_para_rodar = casos
# ============================================================

casos_para_rodar = casos

resultados = {}

for caso in casos_para_rodar:
    resultado = simular_dois_corpos_3d(
        nome_caso=caso["nome"],
        G=caso["G"],
        m1=caso["m1"],
        m2=caso["m2"],
        eps=caso["eps"],
        r1_0=caso["r1"],
        r2_0=caso["r2"],
        v1_0=caso["v1"],
        v2_0=caso["v2"],
        V_CM=caso["V_CM"],
        massa_variavel=caso["massa_variavel"],
        tau1=caso["tau1"],
        tau2=caso["tau2"],
        t_final=caso["t_final"],
        n_points=4000,
        skip=4,
        fps=30,
        dpi=200,
        salvar_video=True,
        mostrar_grafico_estatico=True
    )

    resultados[caso["nome"]] = resultado

